services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    labels:
      - wud.watch.digest=true
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/data
    networks:
      - homelab

networks:
  homelab:
    external: true
