services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2026.8.3
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Lisbon
