services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    restart: unless-stopped
    networks:
      - homelab
    labels:
      - "wud.watch=true"
      - "wud.watch.digest=true"
      - "wud.display.name=Excalidraw"

networks:
  homelab:
    external: true
